# General setting
is:
  keycloak:
    admin:
      user: admin
      password: admin

server:
  port: 8888

# Keycloak settings
keycloak:
  realm: IS Test
  auth-server-url: http://192.168.56.105:8090/auth
  ssl-required: none
  resource: is-keycloak
  use-resource-role-mappings: true
  bearer-only: true
  cors: true
  principal-attribute: preferred_username
